---
version: '3.7'
services:
  bbugyi200.bugyi.tools:
    build:
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bugyi/tools:delegated
    working_dir: /bugyi/tools
    environment:
      - BETTER_EXCEPTIONS
      - CC_REPO_URL
